version: "3"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    depends_on:
      - db
    env_file: .env
  db:
    restart: always
    image: postgres:9.6.2
    ports:
      - "5432:5432"
    env_file: .env